### ISSUE TITLE
Collision and decimate modifier

### ISSUE THREAD

**Issue by lukastomasek** [lukastomasek/blender-automation-tools#4]
Modifiers -> + Add Modifier -> Collision and Decimate

**Comment by Lauriepc** [comment]
https://docs.google.com/document/d/1UZVHVROdbnWFJATT-PnoRUZ5j9nBbaqzSBvj_PGpKbA/edit#heading=h.p1zfkqiy0rsh

This is exactly the steps we take for the collision and decimate.
